import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/provider/query-provider";
import ErrorBoundary from "@/errors/ErrorBoundary";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const googleSansCode = localFont({
  src: [
    { path: "../public/fonts/GoogleSansCode-Light.ttf", weight: "300" },
    { path: "../public/fonts/GoogleSansCode-Regular.ttf", weight: "400" },
    { path: "../public/fonts/GoogleSansCode-Medium.ttf", weight: "500" },
    { path: "../public/fonts/GoogleSansCode-SemiBold.ttf", weight: "600" },
    { path: "../public/fonts/GoogleSansCode-Bold.ttf", weight: "700" },
  ],
  variable: "--font-google-sans-code",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${googleSansCode.variable} ${plusJakartaSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
              <QueryProvider>
                <Toaster position="bottom-right" />
                <ErrorBoundary>{children}</ErrorBoundary>
          </QueryProvider>
        </body>
    </html>
  );
}
