export const COUNTRY_LIST = [
  { id: 1, name: "Afghanistan", code: "AF" },
  { id: 2, name: "Albania", code: "AL" },
  { id: 3, name: "Algeria", code: "DZ" },
  { id: 4, name: "Argentina", code: "AR" },
  { id: 5, name: "Armenia", code: "AM" },
  { id: 6, name: "Australia", code: "AU" },
  { id: 7, name: "Austria", code: "AT" },
  { id: 8, name: "Azerbaijan", code: "AZ" },
  { id: 9, name: "Bahrain", code: "BH" },
  { id: 10, name: "Bangladesh", code: "BD" },
  { id: 11, name: "Belgium", code: "BE" },
  { id: 12, name: "Brazil", code: "BR" },
  { id: 13, name: "Bulgaria", code: "BG" },
  { id: 14, name: "Canada", code: "CA" },
  { id: 15, name: "Chile", code: "CL" },
  { id: 16, name: "China", code: "CN" },
  { id: 17, name: "Colombia", code: "CO" },
  { id: 18, name: "Croatia", code: "HR" },
  { id: 19, name: "Cyprus", code: "CY" },
  { id: 20, name: "Czechia", code: "CZ" },
  { id: 21, name: "Denmark", code: "DK" },
  { id: 22, name: "Egypt", code: "EG" },
  { id: 23, name: "Estonia", code: "EE" },
  { id: 24, name: "Finland", code: "FI" },
  { id: 25, name: "France", code: "FR" },
  { id: 26, name: "Georgia", code: "GE" },
  { id: 27, name: "Germany", code: "DE" },
  { id: 28, name: "Ghana", code: "GH" },
  { id: 29, name: "Greece", code: "GR" },
  { id: 30, name: "Hong Kong", code: "HK" },
  { id: 31, name: "Hungary", code: "HU" },
  { id: 32, name: "India", code: "IN" },
  { id: 33, name: "Indonesia", code: "ID" },
  { id: 34, name: "Iraq", code: "IQ" },
  { id: 35, name: "Ireland", code: "IE" },
  { id: 36, name: "Israel", code: "IL" },
  { id: 37, name: "Italy", code: "IT" },
  { id: 38, name: "Japan", code: "JP" },
  { id: 39, name: "Jordan", code: "JO" },
  { id: 40, name: "Kazakhstan", code: "KZ" },
  { id: 41, name: "Kenya", code: "KE" },
  { id: 42, name: "Kuwait", code: "KW" },
  { id: 43, name: "Latvia", code: "LV" },
  { id: 44, name: "Lebanon", code: "LB" },
  { id: 45, name: "Lithuania", code: "LT" },
  { id: 46, name: "Luxembourg", code: "LU" },
  { id: 47, name: "Malaysia", code: "MY" },
  { id: 48, name: "Maldives", code: "MV" },
  { id: 49, name: "Mexico", code: "MX" },
  { id: 50, name: "Morocco", code: "MA" },
  { id: 51, name: "Netherlands", code: "NL" },
  { id: 52, name: "New Zealand", code: "NZ" },
  { id: 53, name: "Nigeria", code: "NG" },
  { id: 54, name: "Norway", code: "NO" },
  { id: 55, name: "Oman", code: "OM" },
  { id: 56, name: "Pakistan", code: "PK" },
  { id: 57, name: "Palestine", code: "PS" },
  { id: 58, name: "Peru", code: "PE" },
  { id: 59, name: "Philippines", code: "PH" },
  { id: 60, name: "Poland", code: "PL" },
  { id: 61, name: "Portugal", code: "PT" },
  { id: 62, name: "Qatar", code: "QA" },
  { id: 63, name: "Romania", code: "RO" },
  { id: 64, name: "Russia", code: "RU" },
  { id: 65, name: "Saudi Arabia", code: "SA" },
  { id: 66, name: "Singapore", code: "SG" },
  { id: 67, name: "South Africa", code: "ZA" },
  { id: 68, name: "South Korea", code: "KR" },
  { id: 69, name: "Spain", code: "ES" },
  { id: 70, name: "Sri Lanka", code: "LK" },
  { id: 71, name: "Sweden", code: "SE" },
  { id: 72, name: "Switzerland", code: "CH" },
  { id: 73, name: "Taiwan", code: "TW" },
  { id: 74, name: "Thailand", code: "TH" },
  { id: 75, name: "Turkey", code: "TR" },
  { id: 76, name: "Ukraine", code: "UA" },
  { id: 77, name: "United Arab Emirates", code: "AE" },
  { id: 78, name: "United Kingdom", code: "GB" },
  { id: 79, name: "United States", code: "US" },
  { id: 80, name: "Uzbekistan", code: "UZ" },
  { id: 81, name: "Vietnam", code: "VN" },
];
