export const INDUSTRY_LIST = [
  { id: 1, name: "Accounting" },
  { id: 2, name: "Advertising & Marketing" },
  { id: 3, name: "Aerospace & Defense" },
  { id: 4, name: "Agriculture" },
  { id: 5, name: "Architecture & Design" },
  { id: 6, name: "Artificial Intelligence" },
  { id: 7, name: "Automotive" },
  { id: 8, name: "Banking" },
  { id: 9, name: "Biotechnology" },
  { id: 10, name: "Blockchain & Crypto" },
  { id: 11, name: "Business Consulting" },
  { id: 12, name: "Chemicals" },
  { id: 13, name: "Clean Energy" },
  { id: 14, name: "Cloud Computing" },
  { id: 15, name: "Construction" },
  { id: 16, name: "Consumer Goods" },
  { id: 17, name: "Cybersecurity" },
  { id: 18, name: "Data Analytics" },
  { id: 19, name: "E-commerce" },
  { id: 20, name: "EdTech" },
  { id: 21, name: "Education" },
  { id: 22, name: "Electronics" },
  { id: 23, name: "Energy & Utilities" },
  { id: 24, name: "Engineering Services" },
  { id: 25, name: "Environmental Services" },
  { id: 26, name: "Events & Entertainment" },
  { id: 27, name: "Fashion & Apparel" },
  { id: 28, name: "Finance" },
  { id: 29, name: "FinTech" },
  { id: 30, name: "Food & Beverage" },
  { id: 31, name: "Gaming" },
  { id: 32, name: "Government & Public Sector" },
  { id: 33, name: "Healthcare" },
  { id: 34, name: "HealthTech" },
  { id: 35, name: "Hospitality" },
  { id: 36, name: "HR & Recruiting" },
  { id: 37, name: "Insurance" },
  { id: 38, name: "Information Technology" },
  { id: 39, name: "Internet of Things (IoT)" },
  { id: 40, name: "Investment & Venture Capital" },
  { id: 41, name: "Legal Services" },
  { id: 42, name: "Logistics & Supply Chain" },
  { id: 43, name: "Manufacturing" },
  { id: 44, name: "Media and Entertainment" },
  { id: 45, name: "Mining & Metals" },
  { id: 46, name: "Non-Profit & NGO" },
  { id: 47, name: "Oil & Gas" },
  { id: 48, name: "Pharmaceuticals" },
  { id: 49, name: "Professional Services" },
  { id: 50, name: "Real Estate" },
  { id: 51, name: "Retail" },
  { id: 52, name: "Robotics" },
  { id: 53, name: "SaaS" },
  { id: 54, name: "Security Services" },
  { id: 55, name: "Sports & Fitness" },
  { id: 56, name: "Telecommunications" },
  { id: 57, name: "Tourism & Travel" },
  { id: 58, name: "Transportation" },
  { id: 59, name: "Wholesale & Distribution" },
  { id: 60, name: "Other" },
];
